[mongodb]
mongodb-dev.cineniti.in

[catalogue]
catalogue-dev.cineniti.in

[redis]
redis-dev.cineniti.in

[user]
user-dev.cineniti.in

[mysql]
mysql-dev.cineniti.in   

[cart]
cart-dev.cineniti.in

[shipping]
shipping-dev.cineniti.in


[rabbitmq]
rabbitmq-dev.cineniti.in
[payment]
payment-dev.cineniti.in

[frontend]
frontend-dev.cineniti.in

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.cineniti.in
REDIS_HOST=redis-dev.cineniti.in
MYSQL_HOST=mysql-dev.cineniti.in
USER_HOST=user-dev.cineniti.in
CART_HOST=cart-dev.cineniti.in
SHIPPING_HOST=shipping-dev.cineniti.in
RABBITMQ_HOST=rabbitmq-dev.cineniti.in
PAYMENT_HOST=payment-dev.cineniti.in
